import type {
  Activity,
  Application,
  Team,
  Milestone,
  Submission,
  Certificate,
  MessageChannel,
  AuditLog,
  User,
} from '@/types';

export const MOCK_USERS_LIST: User[] = [
  {
    id: 'user-vedant-nikumbh',
    name: 'Vedant Balvant Nikumbh',
    email: 'vedant.nikumbh@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=VedantNikumbh',
    institutionalId: '24108B0021',
    isOnline: true,
  },
  {
    id: 'user-yash-khanvilkar',
    name: 'Yash Sachin Khanvilkar',
    email: 'yash.khanvilkar@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=YashKhanvilkar',
    institutionalId: '24108B0022',
    isOnline: true,
  },
  {
    id: 'user-paras-shah',
    name: 'Paras Rajeev Shah',
    email: 'paras.shah@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=ParasShah',
    institutionalId: '24108B0023',
    isOnline: true,
  },
  {
    id: 'user-vedant-patole',
    name: 'Vedant Nilesh Patole',
    email: 'vedant.patole@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=VedantPatole',
    institutionalId: '24108B0024',
    isOnline: true,
  },
  {
    id: 'user-sheetal-patil',
    name: 'Dr. Sheetal Patil',
    email: 'sheetal.patil@vit.edu.in',
    role: 'COORDINATOR',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=SheetalPatil',
    institutionalId: 'FAC-SPATIL-2026',
    isOnline: true,
  },
  {
    id: 'user-akhil-masurkar',
    name: 'Prof. Akhil Masurkar',
    email: 'akhil.masurkar@vit.edu.in',
    role: 'COORDINATOR',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=AkhilMasurkar',
    institutionalId: 'FAC-2012-005',
    isOnline: true,
  },
  {
    id: 'user-harshad-panchal',
    name: 'Harshad Prakash Panchal',
    email: 'harshad.panchal@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=HarshadPanchal',
    institutionalId: '24108B0001',
    isOnline: true,
  },
  {
    id: 'user-partner-001',
    name: 'Rahul Kapoor',
    email: 'rahul@techcorp.com',
    role: 'INDUSTRY_PARTNER',
    department: 'TechCorp Solutions',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Rahul',
  },
];

export const MOCK_USERS: Record<string, User> = {
  STUDENT: MOCK_USERS_LIST[0],
  COORDINATOR: MOCK_USERS_LIST[4],
  INDUSTRY_PARTNER: MOCK_USERS_LIST[7],
  SUPER_ADMIN: {
    id: 'user-admin-001',
    name: 'Dean Academic Affairs',
    email: 'academic.dean@vit.edu.in',
    role: 'SUPER_ADMIN',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Dean',
    isOnline: true,
  },
};

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'activity-001',
    title: 'Semester 5 Mini Project',
    description: 'Mini project curriculum for Semester 5 students of the Electronics and Computer Science Department.',
    category: 'CAPSTONE',
    status: 'IN_PROGRESS',
    department: 'Electronics and Computer Science',
    capacity: 120,
    filledSeats: 12,
    teamSizeMin: 4,
    teamSizeMax: 4,
    applicationDeadline: '2026-10-15T23:59:00Z',
    prerequisites: ['Electronics and Computer Science Core Courses'],
    supervisorId: 'user-sheetal-patil',
    milestones: [],
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
];

export const MOCK_MILESTONES: Milestone[] = [
  {
    id: 'ms-001',
    activityId: 'activity-001',
    title: 'Milestone 1: Problem Formulation & Architecture Specification',
    description: 'System block diagram, technical stack selection, and preliminary architecture blueprint commit.',
    stageNumber: 1,
    status: 'ACCEPTED',
    dueDate: '2026-10-15T23:59:00Z',
    weightage: 20,
    deliverableType: 'PDF',
    createdAt: '2026-08-15T00:00:00Z',
    updatedAt: '2026-09-15T00:00:00Z',
  },
  {
    id: 'ms-002',
    activityId: 'activity-001',
    title: 'Milestone 2: Working Prototype & Code Repository Demonstration',
    description: 'GitHub repository with clean branch commits, passing unit tests, and 5-minute video presentation.',
    stageNumber: 2,
    status: 'OPEN',
    dueDate: '2026-11-01T23:59:00Z',
    weightage: 35,
    deliverableType: 'GITHUB_URL',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'ms-003',
    activityId: 'activity-001',
    title: 'Milestone 3: Final System Integration, Defense Viva & Accreditation',
    description: 'Final production build deployment, comprehensive technical report PDF, and faculty viva examination.',
    stageNumber: 3,
    status: 'NOT_STARTED',
    dueDate: '2026-11-30T23:59:00Z',
    weightage: 45,
    deliverableType: 'PDF',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-01T00:00:00Z',
  },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-mini-1',
    activityId: 'activity-001',
    name: 'Mini 1',
    members: [
      {
        userId: 'user-harshad-panchal',
        user: {
          id: 'user-harshad-panchal',
          name: 'Harshad Prakash Panchal',
          email: 'harshad.panchal@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'LEAD',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-aditya-parmale',
        user: {
          id: 'user-aditya-parmale',
          name: 'Aditya Vijay Parmale',
          email: 'aditya.parmale@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-mayur-naik',
        user: {
          id: 'user-mayur-naik',
          name: 'Mayur Babu Naik',
          email: 'mayur.naik@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-ritesh-yadav',
        user: {
          id: 'user-ritesh-yadav',
          name: 'Ritesh Omprakash Yadav',
          email: 'ritesh.yadav@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
    ],
    mentorId: 'user-sheetal-patil',
    mentor: MOCK_USERS_LIST[4],
    riskLevel: 'ON_TRACK',
    createdAt: '2026-09-15T00:00:00Z',
  },
  {
    id: 'team-mini-6',
    activityId: 'activity-001',
    name: 'Mini 6',
    members: [
      {
        userId: 'user-yash-khanvilkar',
        user: {
          id: 'user-yash-khanvilkar',
          name: 'Yash Sachin Khanvilkar',
          email: 'yash.khanvilkar@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'LEAD',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-paras-shah',
        user: {
          id: 'user-paras-shah',
          name: 'Paras Rajeev Shah',
          email: 'paras.shah@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-vedant-patole',
        user: {
          id: 'user-vedant-patole',
          name: 'Vedant Nilesh Patole',
          email: 'vedant.patole@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-vedant-nikumbh',
        user: {
          id: 'user-vedant-nikumbh',
          name: 'Vedant Balvant Nikumbh',
          email: 'vedant.nikumbh@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
    ],
    mentorId: 'user-sheetal-patil',
    mentor: MOCK_USERS_LIST[4],
    riskLevel: 'ON_TRACK',
    createdAt: '2026-09-15T00:00:00Z',
  },
  {
    id: 'team-mini-8',
    activityId: 'activity-001',
    name: 'Mini 8',
    members: [
      {
        userId: 'user-deven-sonawane',
        user: {
          id: 'user-deven-sonawane',
          name: 'Deven vilas sonawane',
          email: 'deven.sonawane@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'LEAD',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-kshitij-palekar',
        user: {
          id: 'user-kshitij-palekar',
          name: 'Kshitij palekar',
          email: 'kshitij.palekar@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-mihtil-karambe',
        user: {
          id: 'user-mihtil-karambe',
          name: 'Mihtil karambe',
          email: 'mihtil.karambe@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-parth-karalkar',
        user: {
          id: 'user-parth-karalkar',
          name: 'Parth karalkar',
          email: 'parth.karalkar@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
    ],
    mentorId: 'user-sheetal-patil',
    mentor: MOCK_USERS_LIST[4],
    riskLevel: 'ON_TRACK',
    createdAt: '2026-09-15T00:00:00Z',
  },
];

export const MOCK_SUBMISSIONS: Submission[] = [];

export const MOCK_CERTIFICATES: Certificate[] = [];

export const MOCK_APPLICATIONS: Application[] = [];

export const MOCK_CHANNELS: MessageChannel[] = [
  {
    id: 'ch-001',
    type: 'TEAM_WORKSPACE',
    name: '#Mini-6-workspace',
    teamId: 'team-mini-6',
    activityId: 'activity-001',
    participantIds: [
      'user-vedant-nikumbh',
      'user-yash-khanvilkar',
      'user-paras-shah',
      'user-vedant-patole',
      'user-sheetal-patil',
    ],
    unreadCount: 0,
  },
  {
    id: 'ch-002',
    type: 'TEAM_WORKSPACE',
    name: '#Mini-1-workspace',
    teamId: 'team-mini-1',
    activityId: 'activity-001',
    participantIds: ['user-harshad-panchal', 'user-sheetal-patil'],
    unreadCount: 0,
  },
  {
    id: 'ch-003',
    type: 'TEAM_WORKSPACE',
    name: '#Mini-8-workspace',
    teamId: 'team-mini-8',
    activityId: 'activity-001',
    participantIds: ['user-deven-sonawane', 'user-sheetal-patil'],
    unreadCount: 0,
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [];
