import type {
  Activity,
  Application,
  Team,
  Milestone,
  Submission,
  Certificate,
  MessageChannel,
  AuditLog,
  User,
} from '@/types';

export const MOCK_USERS_LIST: User[] = [
  {
    id: 'user-student-001',
    name: 'Siddharth Chen',
    email: 'siddharth.chen@university.edu',
    role: 'STUDENT',
    department: 'CS & AI',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Siddharth',
    institutionalId: 'VC-2026-891',
    isOnline: true,
  },
  {
    id: 'user-student-002',
    name: 'Maya Lin',
    email: 'maya.lin@university.edu',
    role: 'STUDENT',
    department: 'CS & AI',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=MayaLin',
    institutionalId: 'VC-2026-442',
    isOnline: true,
  },
  {
    id: 'user-student-003',
    name: 'Tariq Ahmed',
    email: 'tariq.ahmed@university.edu',
    role: 'STUDENT',
    department: 'Electrical Engineering',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Tariq',
    institutionalId: 'VC-2026-218',
  },
  {
    id: 'user-student-004',
    name: 'Chloe Dubois',
    email: 'chloe.dubois@university.edu',
    role: 'STUDENT',
    department: 'Bioinformatics',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Chloe',
    institutionalId: 'VC-2026-503',
  },
  {
    id: 'user-mentor-001',
    name: 'Dr. Eleanor Vance',
    email: 'eleanor.vance@university.edu',
    role: 'FACULTY_MENTOR',
    department: 'CS & AI',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Eleanor',
    institutionalId: 'FAC-2019-042',
    isOnline: true,
  },
  {
    id: 'user-mentor-002',
    name: 'Dr. Elena Rostova',
    email: 'elena.rostova@university.edu',
    role: 'FACULTY_MENTOR',
    department: 'Bioinformatics',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=ElenaBio',
  },
  {
    id: 'user-coord-001',
    name: 'Prof. Arjun Mehta',
    email: 'arjun.mehta@university.edu',
    role: 'COORDINATOR',
    department: 'CS & AI',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Arjun',
  },
  {
    id: 'user-partner-001',
    name: 'Rahul Kapoor',
    email: 'rahul.kapoor@techcorp.com',
    role: 'INDUSTRY_PARTNER',
    department: 'TechCorp Solutions',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Rahul',
  },
];

export const MOCK_USERS: Record<string, User> = {
  STUDENT: MOCK_USERS_LIST[0],
  FACULTY_MENTOR: MOCK_USERS_LIST[4],
  COORDINATOR: MOCK_USERS_LIST[6],
  EXTERNAL_REVIEWER: {
    id: 'user-reviewer-001',
    name: 'Dr. Priya Nair',
    email: 'priya.nair@externalorg.com',
    role: 'EXTERNAL_REVIEWER',
    department: 'External Review Board',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Priya',
    isOnline: false,
  },
  INDUSTRY_PARTNER: MOCK_USERS_LIST[7],
  SUPER_ADMIN: {
    id: 'user-admin-001',
    name: 'Dean Rita Sharma',
    email: 'rita.sharma@university.edu',
    role: 'SUPER_ADMIN',
    department: 'Dean of Academic Affairs',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Rita',
    isOnline: true,
  },
};

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'activity-001',
    title: 'National AI & Autonomous Systems Hackathon 2026',
    description: 'A 72-hour multidisciplinary hackathon challenging teams to build scalable autonomous systems using machine learning, robotics, and edge computing.',
    category: 'HACKATHON',
    status: 'IN_PROGRESS',
    department: 'CS & AI',
    capacity: 30,
    filledSeats: 24,
    teamSizeMin: 3,
    teamSizeMax: 5,
    applicationDeadline: '2026-09-15T23:59:00Z',
    prerequisites: ['Python', 'ML Fundamentals', 'Git'],
    supervisorId: 'user-mentor-001',
    milestones: [],
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'activity-002',
    title: 'Autonomous Micro-Grid Simulation: Reinforcement Learning Controller',
    description: 'Capstone project designing and implementing a reinforcement learning-based controller for autonomous urban micro-grid nodes.',
    category: 'CAPSTONE',
    status: 'IN_PROGRESS',
    department: 'CS & AI',
    capacity: 8,
    filledSeats: 7,
    teamSizeMin: 2,
    teamSizeMax: 4,
    applicationDeadline: '2026-08-31T23:59:00Z',
    prerequisites: ['Reinforcement Learning', 'Systems Engineering', 'Python', 'Senior Year'],
    supervisorId: 'user-mentor-001',
    milestones: [],
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'activity-003',
    title: 'De Novo Peptide Sequencing Engine using Deep Learning',
    description: 'Research project developing a novel neural architecture for de novo protein sequence prediction from mass spectrometry data.',
    category: 'RESEARCH',
    status: 'IN_PROGRESS',
    department: 'Bioinformatics',
    capacity: 5,
    filledSeats: 3,
    teamSizeMin: 2,
    teamSizeMax: 3,
    applicationDeadline: '2026-08-15T23:59:00Z',
    prerequisites: ['Bioinformatics', 'PyTorch', 'Protein Biochemistry'],
    supervisorId: 'user-mentor-002',
    milestones: [],
    createdAt: '2026-07-15T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'activity-004',
    title: 'Distributed EEG Signal Processing Pipeline',
    description: 'Advanced research into real-time distributed signal filtering topologies for neural interface applications.',
    category: 'RESEARCH',
    status: 'OPEN_FOR_APPLICATIONS',
    department: 'CS & AI',
    capacity: 12,
    filledSeats: 7,
    teamSizeMin: 3,
    teamSizeMax: 4,
    applicationDeadline: '2026-10-15T23:59:00Z',
    prerequisites: ['Signal Processing', 'Distributed Systems', 'Python/C++'],
    supervisorId: 'user-mentor-001',
    milestones: [],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-10T00:00:00Z',
  },
  {
    id: 'activity-005',
    title: 'Sustainable Urban Mobility Analytics Platform',
    description: 'Industry-sponsored capstone to build a real-time analytics dashboard for smart city transportation data.',
    category: 'INDUSTRY_PROJECT',
    status: 'OPEN_FOR_APPLICATIONS',
    department: 'CS & AI',
    capacity: 20,
    filledSeats: 4,
    teamSizeMin: 3,
    teamSizeMax: 5,
    applicationDeadline: '2026-10-20T23:59:00Z',
    prerequisites: ['Data Engineering', 'React', 'PostgreSQL'],
    supervisorId: 'user-coord-001',
    milestones: [],
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-10T00:00:00Z',
  },
];

export const MOCK_MILESTONES: Milestone[] = [
  {
    id: 'ms-001',
    activityId: 'activity-001',
    teamId: 'team-001',
    title: 'Milestone 1: System Architecture & Design Document',
    description: 'Submit a detailed architecture document covering system design, tech stack choices, and scalability considerations.',
    stageNumber: 1,
    status: 'ACCEPTED',
    dueDate: '2026-10-01T23:59:00Z',
    weightage: 20,
    deliverableType: 'PDF',
    mentorFeedback: 'Excellent architectural revision on the streaming pipeline. Well done.',
    rubricCriteria: [
      { id: 'rc-001', milestoneId: 'ms-001', title: 'Technical Architecture & Feasibility', description: 'Soundness of design', maxPoints: 10, descriptors: ['Signal pipeline latency < 45ms', 'Scalable fault-tolerant ingestion'] },
      { id: 'rc-002', milestoneId: 'ms-001', title: 'Academic & Empirical Rigor', description: 'Evidence-based reasoning', maxPoints: 10 },
      { id: 'rc-003', milestoneId: 'ms-001', title: 'Documentation & Code Standards', description: 'Clarity and completeness', maxPoints: 10 },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-02T00:00:00Z',
  },
  {
    id: 'ms-002',
    activityId: 'activity-001',
    teamId: 'team-001',
    title: 'Milestone 2: Working Prototype & Demo Recording',
    description: 'Submit a working prototype with a 5-minute demo video, GitHub repository, and performance benchmark report.',
    stageNumber: 2,
    status: 'OPEN',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
    weightage: 35,
    deliverableType: 'GITHUB_URL',
    rubricCriteria: [
      { id: 'rc-004', milestoneId: 'ms-002', title: 'Prototype Functionality', description: 'Core features working as specified', maxPoints: 15 },
      { id: 'rc-005', milestoneId: 'ms-002', title: 'Code Quality & Documentation', description: 'Clean, documented codebase', maxPoints: 10 },
      { id: 'rc-006', milestoneId: 'ms-002', title: 'Demo Clarity & Innovation', description: 'Presentation quality and originality', maxPoints: 10 },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'ms-003',
    activityId: 'activity-001',
    teamId: 'team-001',
    title: 'Milestone 3: Final Presentation & Report',
    description: 'Final capstone defense with full project report, lessons learned, and future roadmap.',
    stageNumber: 3,
    status: 'NOT_STARTED',
    dueDate: '2026-11-15T23:59:00Z',
    weightage: 45,
    deliverableType: 'PDF',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-001',
    activityId: 'activity-001',
    name: 'Team NexGen',
    members: [
      { userId: 'user-student-001', user: MOCK_USERS_LIST[0], role: 'LEAD', joinedAt: '2026-09-16T00:00:00Z' },
      { userId: 'user-student-002', user: MOCK_USERS_LIST[1], role: 'CONTRIBUTOR', joinedAt: '2026-09-16T00:00:00Z' },
      { userId: 'user-student-003', user: MOCK_USERS_LIST[2], role: 'CONTRIBUTOR', joinedAt: '2026-09-16T00:00:00Z' },
    ],
    mentorId: 'user-mentor-001',
    mentor: MOCK_USERS_LIST[4],
    riskLevel: 'ON_TRACK',
    createdAt: '2026-09-16T00:00:00Z',
  },
  {
    id: 'team-002',
    activityId: 'activity-004',
    name: 'Team NeuroMesh',
    members: [
      { userId: 'user-student-002', user: MOCK_USERS_LIST[1], role: 'LEAD', joinedAt: '2026-09-10T00:00:00Z' },
    ],
    mentorId: 'user-mentor-001',
    mentor: MOCK_USERS_LIST[4],
    riskLevel: 'AT_RISK',
    riskReason: 'Overdue 3 days: Architecture Spec. Code commits stalled 72h.',
    createdAt: '2026-09-10T00:00:00Z',
  },
  {
    id: 'team-003',
    activityId: 'activity-002',
    name: 'Team HyperGrid IoT',
    members: [
      { userId: 'user-student-003', user: MOCK_USERS_LIST[2], role: 'LEAD', joinedAt: '2026-09-05T00:00:00Z' },
    ],
    mentorId: 'user-mentor-001',
    mentor: MOCK_USERS_LIST[4],
    riskLevel: 'NEEDS_ATTENTION',
    riskReason: 'Changes Requested: 2 consecutive rejections. Rubric Criterion 3.2 unaddressed.',
    createdAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'team-004',
    activityId: 'activity-003',
    name: 'Team BioSynth AI',
    members: [
      { userId: 'user-student-004', user: MOCK_USERS_LIST[3], role: 'LEAD', joinedAt: '2026-09-01T00:00:00Z' },
    ],
    mentorId: 'user-mentor-002',
    mentor: MOCK_USERS_LIST[5],
    riskLevel: 'NEEDS_ATTENTION',
    riskReason: 'Inactive: 5 days without commit. GitHub repo inactivity flagged.',
    createdAt: '2026-09-01T00:00:00Z',
  },
];

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-001-v1',
    milestoneId: 'ms-001',
    teamId: 'team-001',
    submittedById: 'user-student-001',
    submittedBy: MOCK_USERS_LIST[0],
    version: 1,
    fileUrl: 'https://storage.example.com/submissions/sub-001-v1.pdf',
    fileName: 'Team_NexGen_Architecture_v1.pdf',
    fileSizeBytes: 2_450_000,
    checksumSha256: 'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456',
    studentNote: 'Initial architecture document. Covers all core system components.',
    submittedAt: '2026-09-28T14:30:00Z',
    mentorPublicFeedback: 'Good start. Please address the buffer overrun risk at §3.2 and add edge compute fallback specification.',
    gradedAt: '2026-09-29T10:00:00Z',
    gradedById: 'user-mentor-001',
  },
  {
    id: 'sub-001-v2',
    milestoneId: 'ms-001',
    teamId: 'team-001',
    submittedById: 'user-student-001',
    submittedBy: MOCK_USERS_LIST[0],
    version: 2,
    fileUrl: 'https://storage.example.com/submissions/sub-001-v2.pdf',
    fileName: 'Team_NexGen_Architecture_v2.pdf',
    fileSizeBytes: 3_100_000,
    checksumSha256: '7e9b4a1f2c3d4e5f6789012345678901234567890abcdef1234567890abcdef',
    studentNote: 'Addressed previous review comments regarding buffer overrun risks under 128-channel sampling rates. Included synthetic stress testing report in Appendix B.',
    submittedAt: '2026-10-01T09:40:00Z',
    rubricScores: [
      { criterionId: 'rc-001', score: 8, evaluatorId: 'user-mentor-001' },
      { criterionId: 'rc-002', score: 9, evaluatorId: 'user-mentor-001' },
      { criterionId: 'rc-003', score: 7, evaluatorId: 'user-mentor-001' },
    ],
    mentorPrivateNote: 'Student demonstrated significant turnaround on thread contention issue. Recommended for departmental showcase if final evaluation passes.',
    mentorPublicFeedback: 'Excellent architectural revision. Please finalize docstrings for the WebSocket bridge before the midterm defense.',
    gradedAt: '2026-10-02T11:42:00Z',
    gradedById: 'user-mentor-001',
  },
];

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-001',
    type: 'PLATFORM_ISSUED',
    studentId: 'user-student-001',
    student: MOCK_USERS_LIST[0],
    activityId: 'activity-001',
    activityTitle: 'National AI & Autonomous Systems Hackathon 2026 — First Place & Best Technical Architecture',
    issueDate: '2026-10-24T00:00:00Z',
    verificationHash: '8f4a9b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9',
    verificationUrl: 'https://vbridgeconnect.university.edu/verify/8f4a9b',
    blockNumber: '482910',
    signatories: ['Dr. Eleanor Vance', 'Dean Rita Sharma'],
    disclaimer: 'Official university-issued credential, cryptographically verified and recorded on the institutional ledger.',
  },
  {
    id: 'cert-002',
    type: 'PLATFORM_ISSUED',
    studentId: 'user-student-001',
    student: MOCK_USERS_LIST[0],
    activityId: 'activity-002',
    activityTitle: 'Autonomous Micro-Grid Simulation: Reinforcement Learning Grid Controller — Distinction',
    issueDate: '2026-11-15T00:00:00Z',
    verificationHash: '3c72ef89ab12cd34ef56789012345678901234567890abcdef1234567890ab12',
    verificationUrl: 'https://vbridgeconnect.university.edu/verify/3c72ef',
    blockNumber: '491042',
    signatories: ['Dr. Eleanor Vance', 'Prof. Arjun Mehta'],
    disclaimer: 'Official university-issued credential, cryptographically verified and recorded on the institutional ledger.',
  },
  {
    id: 'cert-003',
    type: 'SELF_REPORTED',
    studentId: 'user-student-001',
    student: MOCK_USERS_LIST[0],
    activityTitle: 'Advanced Deep Learning Specialization',
    issueDate: '2026-10-12T00:00:00Z',
    externalProvider: 'DeepLearning.AI / Coursera',
    uploadReceiptUrl: 'https://storage.example.com/self-reported/cert-003-receipt.pdf',
    isVerifiedByFaculty: false,
    disclaimer: 'EXTERNAL / NOT AUDITED BY UNIVERSITY AUTHORITIES (FR-115). This certificate was self-reported by the student and has not been verified by university authorities. It will NOT appear in official accreditation or NAAC reports.',
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-001',
    activityId: 'activity-001',
    studentId: 'user-student-001',
    student: MOCK_USERS_LIST[0],
    status: 'ACCEPTED',
    statementOfPurpose: 'I have extensive experience in autonomous systems and ML pipelines. Our team has previously won 2 hackathons at the state level.',
    portfolioUrl: 'https://github.com/siddharth-chen',
    gpa: 9.1,
    submittedAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-16T10:00:00Z',
  },
  {
    id: 'app-002',
    activityId: 'activity-002',
    studentId: 'user-student-001',
    student: MOCK_USERS_LIST[0],
    status: 'ACCEPTED',
    statementOfPurpose: 'Deeply interested in applying RL to energy optimization problems. Have completed a research paper in this domain.',
    gpa: 9.1,
    submittedAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-05T10:00:00Z',
  },
];

export const MOCK_CHANNELS: MessageChannel[] = [
  {
    id: 'ch-001',
    type: 'TEAM_WORKSPACE',
    name: '#team-nexgen-hackathon',
    teamId: 'team-001',
    activityId: 'activity-001',
    participantIds: ['user-student-001', 'user-student-002', 'user-student-003', 'user-mentor-001'],
    unreadCount: 2,
  },
  {
    id: 'ch-002',
    type: 'OFFICE_HOURS',
    name: '#mentor-office-hours',
    teamId: 'team-001',
    participantIds: ['user-student-001', 'user-mentor-001'],
    unreadCount: 0,
  },
  {
    id: 'ch-003',
    type: 'ANNOUNCEMENT',
    name: '#dept-announcements',
    activityId: 'activity-001',
    participantIds: ['user-student-001', 'user-coord-001'],
    unreadCount: 1,
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-001',
    actorId: 'user-mentor-001',
    actor: MOCK_USERS_LIST[4],
    entityType: 'MILESTONE',
    entityId: 'ms-001',
    action: 'milestone.accepted',
    prevState: 'SUBMITTED',
    newState: 'ACCEPTED',
    timestampUtc: '2026-10-02T11:42:00Z',
    ipAddress: '10.0.0.5',
  },
  {
    id: 'audit-002',
    actorId: 'user-student-001',
    actor: MOCK_USERS_LIST[0],
    entityType: 'SUBMISSION',
    entityId: 'sub-001-v2',
    action: 'submission.created',
    newState: 'SUBMITTED',
    timestampUtc: '2026-10-01T09:40:00Z',
    ipAddress: '10.0.0.12',
  },
  {
    id: 'audit-003',
    actorId: 'user-coord-001',
    actor: MOCK_USERS_LIST[6],
    entityType: 'APPLICATION',
    entityId: 'app-001',
    action: 'application.accepted',
    prevState: 'SHORTLISTED',
    newState: 'ACCEPTED',
    timestampUtc: '2026-09-16T10:00:00Z',
    ipAddress: '10.0.0.1',
  },
  {
    id: 'audit-004',
    actorId: 'user-coord-001',
    actor: MOCK_USERS_LIST[6],
    entityType: 'CERTIFICATE',
    entityId: 'cert-001',
    action: 'certificate.issued',
    newState: 'PLATFORM_ISSUED',
    timestampUtc: '2026-10-24T08:00:00Z',
    ipAddress: '10.0.0.1',
  },
];
