import type {
  Activity,
  Application,
  Team,
  Milestone,
  Submission,
  Certificate,
  MessageChannel,
  AuditLog,
  User,
} from '@/types';

export const MOCK_USERS_LIST: User[] = [
  {
    id: 'user-vedant-nikumbh',
    name: 'Vedant Balvant Nikumbh',
    email: 'vedant.nikumbh@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=VedantNikumbh',
    institutionalId: '24108B0021',
    isOnline: true,
  },
  {
    id: 'user-yash-khanvilkar',
    name: 'Yash Sachin Khanvilkar',
    email: 'yash.khanvilkar@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=YashKhanvilkar',
    institutionalId: '24108B0022',
    isOnline: true,
  },
  {
    id: 'user-paras-shah',
    name: 'Paras Rajeev Shah',
    email: 'paras.shah@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=ParasShah',
    institutionalId: '24108B0023',
    isOnline: true,
  },
  {
    id: 'user-vedant-patole',
    name: 'Vedant Nilesh Patole',
    email: 'vedant.patole@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=VedantPatole',
    institutionalId: '24108B0024',
    isOnline: true,
  },
  {
    id: 'user-sheetal-patil',
    name: 'Dr. Sheetal Patil',
    email: 'sheetal.patil@vit.edu.in',
    role: 'COORDINATOR',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=SheetalPatil',
    institutionalId: 'FAC-SPATIL-2026',
    isOnline: true,
  },
  {
    id: 'user-akhil-masurkar',
    name: 'Prof. Akhil Masurkar',
    email: 'akhil.masurkar@vit.edu.in',
    role: 'COORDINATOR',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=AkhilMasurkar',
    institutionalId: 'FAC-2012-005',
    isOnline: true,
  },
  {
    id: 'user-harshad-panchal',
    name: 'Harshad Prakash Panchal',
    email: 'harshad.panchal@vit.edu.in',
    role: 'STUDENT',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=HarshadPanchal',
    institutionalId: '24108B0001',
    isOnline: true,
  },
  {
    id: 'user-partner-001',
    name: 'Rahul Kapoor',
    email: 'rahul@techcorp.com',
    role: 'INDUSTRY_PARTNER',
    department: 'TechCorp Solutions',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Rahul',
  },
];

export const MOCK_USERS: Record<string, User> = {
  STUDENT: MOCK_USERS_LIST[0],
  COORDINATOR: MOCK_USERS_LIST[4],
  INDUSTRY_PARTNER: MOCK_USERS_LIST[7],
  SUPER_ADMIN: {
    id: 'user-admin-001',
    name: 'Dean Academic Affairs',
    email: 'academic.dean@vit.edu.in',
    role: 'SUPER_ADMIN',
    department: 'Electronics and Computer Science',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Dean',
    isOnline: true,
  },
};

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'activity-001',
    title: 'Semester 5 Mini Project',
    description: 'Mini project curriculum for Semester 5 students of the Electronics and Computer Science Department.',
    category: 'CAPSTONE',
    status: 'IN_PROGRESS',
    department: 'Electronics and Computer Science',
    capacity: 120,
    filledSeats: 12,
    teamSizeMin: 4,
    teamSizeMax: 4,
    applicationDeadline: '2026-10-15T23:59:00Z',
    prerequisites: ['Electronics and Computer Science Core Courses'],
    supervisorId: 'user-sheetal-patil',
    milestones: [],
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
];

export const MOCK_MILESTONES: Milestone[] = [];

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-mini-1',
    activityId: 'activity-001',
    name: 'Mini 1',
    members: [
      {
        userId: 'user-harshad-panchal',
        user: {
          id: 'user-harshad-panchal',
          name: 'Harshad Prakash Panchal',
          email: 'harshad.panchal@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'LEAD',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-aditya-parmale',
        user: {
          id: 'user-aditya-parmale',
          name: 'Aditya Vijay Parmale',
          email: 'aditya.parmale@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-mayur-naik',
        user: {
          id: 'user-mayur-naik',
          name: 'Mayur Babu Naik',
          email: 'mayur.naik@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-ritesh-yadav',
        user: {
          id: 'user-ritesh-yadav',
          name: 'Ritesh Omprakash Yadav',
          email: 'ritesh.yadav@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
    ],
    mentorId: 'user-sheetal-patil',
    mentor: MOCK_USERS_LIST[4],
    riskLevel: 'ON_TRACK',
    createdAt: '2026-09-15T00:00:00Z',
  },
  {
    id: 'team-mini-6',
    activityId: 'activity-001',
    name: 'Mini 6',
    members: [
      {
        userId: 'user-yash-khanvilkar',
        user: {
          id: 'user-yash-khanvilkar',
          name: 'Yash Sachin Khanvilkar',
          email: 'yash.khanvilkar@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'LEAD',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-paras-shah',
        user: {
          id: 'user-paras-shah',
          name: 'Paras Rajeev Shah',
          email: 'paras.shah@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-vedant-patole',
        user: {
          id: 'user-vedant-patole',
          name: 'Vedant Nilesh Patole',
          email: 'vedant.patole@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-vedant-nikumbh',
        user: {
          id: 'user-vedant-nikumbh',
          name: 'Vedant Balvant Nikumbh',
          email: 'vedant.nikumbh@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
    ],
    mentorId: 'user-sheetal-patil',
    mentor: MOCK_USERS_LIST[4],
    riskLevel: 'ON_TRACK',
    createdAt: '2026-09-15T00:00:00Z',
  },
  {
    id: 'team-mini-8',
    activityId: 'activity-001',
    name: 'Mini 8',
    members: [
      {
        userId: 'user-deven-sonawane',
        user: {
          id: 'user-deven-sonawane',
          name: 'Deven vilas sonawane',
          email: 'deven.sonawane@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'LEAD',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-kshitij-palekar',
        user: {
          id: 'user-kshitij-palekar',
          name: 'Kshitij palekar',
          email: 'kshitij.palekar@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-mihtil-karambe',
        user: {
          id: 'user-mihtil-karambe',
          name: 'Mihtil karambe',
          email: 'mihtil.karambe@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
      {
        userId: 'user-parth-karalkar',
        user: {
          id: 'user-parth-karalkar',
          name: 'Parth karalkar',
          email: 'parth.karalkar@vit.edu.in',
          role: 'STUDENT',
          department: 'Electronics and Computer Science',
        },
        role: 'CONTRIBUTOR',
        joinedAt: '2026-09-15T00:00:00Z',
      },
    ],
    mentorId: 'user-sheetal-patil',
    mentor: MOCK_USERS_LIST[4],
    riskLevel: 'ON_TRACK',
    createdAt: '2026-09-15T00:00:00Z',
  },
];

export const MOCK_SUBMISSIONS: Submission[] = [];

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-aws-yash',
    type: 'SELF_REPORTED',
    studentId: 'user-yash-khanvilkar',
    student: MOCK_USERS_LIST[1],
    studentName: 'Yash Sachin Khanvilkar',
    studentEmail: 'yash.khanvilkar@vit.edu.in',
    studentInstitutionalId: '24108B0022',
    activityTitle: 'AWS Certified Solutions Architect – Associate',
    externalProvider: 'Amazon Web Services (AWS)',
    issueDate: '2026-08-14T00:00:00Z',
    verificationHash: 'AWS-CERT-99482104-YASH',
    verificationUrl: 'https://aws.amazon.com/verification',
    externalFileUrl: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?auto=format&fit=crop&w=800&q=80',
    uploadReceiptUrl: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?auto=format&fit=crop&w=800&q=80',
    status: 'ACTIVE',
    disclaimer: 'UNVERIFIED STUDENT CLAIM: Excluded from official university transcripts and ABET/NAAC audit submissions (FR-115).',
  },
  {
    id: 'cert-dl-vedant',
    type: 'SELF_REPORTED',
    studentId: 'user-vedant-nikumbh',
    student: MOCK_USERS_LIST[0],
    studentName: 'Vedant Balvant Nikumbh',
    studentEmail: 'vedant.nikumbh@vit.edu.in',
    studentInstitutionalId: '24108B0021',
    activityTitle: 'Deep Learning & Neural Networks Specialization',
    externalProvider: 'DeepLearning.AI / Coursera',
    issueDate: '2026-07-28T00:00:00Z',
    verificationHash: 'COURSERA-DL-773198-VN',
    verificationUrl: 'https://coursera.org/verify/COURSERA-DL-773198',
    externalFileUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80',
    uploadReceiptUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80',
    status: 'ACTIVE',
    disclaimer: 'UNVERIFIED STUDENT CLAIM: Excluded from official university transcripts and ABET/NAAC audit submissions (FR-115).',
  },
  {
    id: 'cert-sih-paras',
    type: 'SELF_REPORTED',
    studentId: 'user-paras-shah',
    student: MOCK_USERS_LIST[2],
    studentName: 'Paras Rajeev Shah',
    studentEmail: 'paras.shah@vit.edu.in',
    studentInstitutionalId: '24108B0023',
    activityTitle: 'Smart India Hackathon 2026 Finalist - IoT & Smart Automation',
    externalProvider: 'Ministry of Education & AICTE',
    issueDate: '2026-09-02T00:00:00Z',
    verificationHash: 'SIH2026-FIN-PARAS-SHAH',
    externalFileUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=800&q=80',
    uploadReceiptUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=800&q=80',
    status: 'ACTIVE',
    disclaimer: 'UNVERIFIED STUDENT CLAIM: Excluded from official university transcripts and ABET/NAAC audit submissions (FR-115).',
  },
  {
    id: 'cert-gcp-harshad',
    type: 'SELF_REPORTED',
    studentId: 'user-harshad-panchal',
    student: MOCK_USERS_LIST[6],
    studentName: 'Harshad Prakash Panchal',
    studentEmail: 'harshad.panchal@vit.edu.in',
    studentInstitutionalId: '24108B0025',
    activityTitle: 'Google Cloud Certified Associate Cloud Engineer',
    externalProvider: 'Google Cloud Certification',
    issueDate: '2026-06-20T00:00:00Z',
    verificationHash: 'GCP-ACE-4490123-HARSHAD',
    verificationUrl: 'https://cloud.google.com/certification',
    externalFileUrl: 'https://images.unsplash.com/photo-1607968565043-36af90dde238?auto=format&fit=crop&w=800&q=80',
    uploadReceiptUrl: 'https://images.unsplash.com/photo-1607968565043-36af90dde238?auto=format&fit=crop&w=800&q=80',
    status: 'ACTIVE',
    disclaimer: 'UNVERIFIED STUDENT CLAIM: Excluded from official university transcripts and ABET/NAAC audit submissions (FR-115).',
  },
  {
    id: 'cert-univ-capstone-yash',
    type: 'PLATFORM_ISSUED',
    studentId: 'user-yash-khanvilkar',
    student: MOCK_USERS_LIST[1],
    studentName: 'Yash Sachin Khanvilkar',
    studentEmail: 'yash.khanvilkar@vit.edu.in',
    studentInstitutionalId: '24108B0022',
    activityId: 'activity-001',
    activityTitle: 'Semester 5 Capstone Mini-Project: Edge AI Industrial Safety Inspection',
    externalProvider: 'Department of Electronics & Computer Science, VIT Autonomous',
    issueDate: '2026-10-01T00:00:00Z',
    verificationHash: '0x8f3c71a9e2d45089bf6711c2a0d5e89b4f2c019a',
    verificationUrl: 'https://ledger.vit.edu/verify/0x8f3c71a9e2d45089bf6711c2a0d5e89b4f2c019a',
    signatories: ['Dr. Sheetal Patil (Lead Guide)', 'Prof. Akhil Masurkar (HOD ECS)'],
    status: 'ACTIVE',
    disclaimer: 'Official university-issued credential, cryptographically verified and recorded on the institutional ledger.',
  },
];

export const MOCK_APPLICATIONS: Application[] = [];

export const MOCK_CHANNELS: MessageChannel[] = [
  {
    id: 'ch-001',
    type: 'TEAM_WORKSPACE',
    name: '#Mini-6-workspace',
    teamId: 'team-mini-6',
    activityId: 'activity-001',
    participantIds: [
      'user-vedant-nikumbh',
      'user-yash-khanvilkar',
      'user-paras-shah',
      'user-vedant-patole',
      'user-sheetal-patil',
    ],
    unreadCount: 0,
  },
  {
    id: 'ch-002',
    type: 'TEAM_WORKSPACE',
    name: '#Mini-1-workspace',
    teamId: 'team-mini-1',
    activityId: 'activity-001',
    participantIds: ['user-harshad-panchal', 'user-sheetal-patil'],
    unreadCount: 0,
  },
  {
    id: 'ch-003',
    type: 'TEAM_WORKSPACE',
    name: '#Mini-8-workspace',
    teamId: 'team-mini-8',
    activityId: 'activity-001',
    participantIds: ['user-deven-sonawane', 'user-sheetal-patil'],
    unreadCount: 0,
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [];
